name: CI Build and Security Scan

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      
    steps:
      - name: ⬇️ Checkout code (Full History)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Set up Node.js and Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install

      - name: 🛠️ Install Phylum CLI
        run: curl -sSfL https://sh.phylum.io/ | sh -s -- -b /usr/local/bin


      - name: 🛡️ Run Phylum Analysis and Generate SBOM File
        run: |
          phylum auth set-token ${{ secrets.PHYLUM_API_KEY }}
          phylum analyze --json --sbom-format cyclonedx . > phylum-security-report.cdx.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬆️ Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: phylum-sbom
          path: phylum-security-report.cdx.json 
          retention-days: 5